<?php

return [
    [
        'key' => 'sales.carriers.ups',
        'name' => 'ups-shipping::app.admin.system.ups',
        'info' => 'ups-shipping::app.admin.system.ups-info',
        'sort' => 3,
        'fields' => [
            [
                'name' => 'title',
                'title' => 'ups-shipping::app.admin.system.title',
                'type' => 'text',
                'depends' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => true,
                'locale_based' => true,
            ], [
                'name' => 'description',
                'title' => 'ups-shipping::app.admin.system.description',
                'type' => 'textarea',
                'channel_based' => true,
                'locale_based' => true,
            ], [
                'name' => 'active',
                'title' => 'ups-shipping::app.admin.system.status',
                'type' => 'boolean',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'mode',
                'title' => 'ups-shipping::app.admin.system.mode',
                'type' => 'select',
                'default' => 'sandbox',
                'options' => [
                    ['title' => 'ups-shipping::app.admin.system.mode-sandbox', 'value' => 'sandbox'],
                    ['title' => 'ups-shipping::app.admin.system.mode-production', 'value' => 'production'],
                ],
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'client_id',
                'title' => 'ups-shipping::app.admin.system.client-id',
                'type' => 'text',
                'validation' => 'required_if:active,1',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'client_secret',
                'title' => 'ups-shipping::app.admin.system.client-secret',
                'type' => 'password',
                'validation' => 'required_if:active,1',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'account_number',
                'title' => 'ups-shipping::app.admin.system.account-number',
                'type' => 'text',
                'info' => 'ups-shipping::app.admin.system.account-number-info',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'services',
                'title' => 'ups-shipping::app.admin.system.allowed-methods',
                'type' => 'multiselect',
                'options' => [
                    ['title' => 'ups-shipping::app.admin.system.service-01', 'value' => '01'],
                    ['title' => 'ups-shipping::app.admin.system.service-02', 'value' => '02'],
                    ['title' => 'ups-shipping::app.admin.system.service-03', 'value' => '03'],
                    ['title' => 'ups-shipping::app.admin.system.service-07', 'value' => '07'],
                    ['title' => 'ups-shipping::app.admin.system.service-08', 'value' => '08'],
                    ['title' => 'ups-shipping::app.admin.system.service-12', 'value' => '12'],
                    ['title' => 'ups-shipping::app.admin.system.service-13', 'value' => '13'],
                    ['title' => 'ups-shipping::app.admin.system.service-14', 'value' => '14'],
                    ['title' => 'ups-shipping::app.admin.system.service-54', 'value' => '54'],
                    ['title' => 'ups-shipping::app.admin.system.service-59', 'value' => '59'],
                    ['title' => 'ups-shipping::app.admin.system.service-65', 'value' => '65'],
                ],
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'weight_unit',
                'title' => 'ups-shipping::app.admin.system.weight-unit',
                'type' => 'select',
                'default' => 'LBS',
                'options' => [
                    ['title' => 'LBS', 'value' => 'LBS'],
                    ['title' => 'KGS', 'value' => 'KGS'],
                ],
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'packaging_type',
                'title' => 'ups-shipping::app.admin.system.packaging-type',
                'type' => 'select',
                'default' => '02',
                'options' => [
                    ['title' => 'ups-shipping::app.admin.system.container-package', 'value' => '02'],
                    ['title' => 'ups-shipping::app.admin.system.container-letter', 'value' => '01'],
                    ['title' => 'ups-shipping::app.admin.system.container-tube', 'value' => '03'],
                    ['title' => 'ups-shipping::app.admin.system.container-pak', 'value' => '04'],
                    ['title' => 'ups-shipping::app.admin.system.container-express-box', 'value' => '21'],
                ],
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'handling_fee_type',
                'title' => 'ups-shipping::app.admin.system.handling-fee-type',
                'type' => 'select',
                'default' => 'fixed',
                'options' => [
                    ['title' => 'ups-shipping::app.admin.system.handling-fee-fixed', 'value' => 'fixed'],
                    ['title' => 'ups-shipping::app.admin.system.handling-fee-percent', 'value' => 'percent'],
                ],
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'handling_fee_amount',
                'title' => 'ups-shipping::app.admin.system.handling-fee',
                'type' => 'number',
                'default' => '0',
                'validation' => 'required_if:active,1|numeric',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'rate_cache_ttl',
                'title' => 'ups-shipping::app.admin.system.rate-cache-ttl',
                'type' => 'number',
                'default' => '15',
                'info' => 'ups-shipping::app.admin.system.rate-cache-ttl-info',
                'validation' => 'required_if:active,1|numeric',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'debug',
                'title' => 'ups-shipping::app.admin.system.debug',
                'type' => 'boolean',
                'channel_based' => true,
                'locale_based' => false,
            ],
        ],
    ],
];
